# Generated by Django 3.0.3 on 2020-02-15 22:47

from django.db import migrations, models
import students.utils.enums
import students.utils.generate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=students.utils.generate.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('matric_number', models.CharField(max_length=8, unique=True)),
                ('college', models.CharField(choices=[(students.utils.enums.Colleges['coleng'], 'COLENG'), (students.utils.enums.Colleges['colbios'], 'COLBIOS'), (students.utils.enums.Colleges['colphys'], 'COLPHYS'), (students.utils.enums.Colleges['colvet'], 'COLVET'), (students.utils.enums.Colleges['colfhec'], 'COLFHEC'), (students.utils.enums.Colleges['colmas'], 'COLMAS'), (students.utils.enums.Colleges['colerm'], 'COLERM'), (students.utils.enums.Colleges['colanim'], 'COLANIM'), (students.utils.enums.Colleges['colamrud'], 'COLAMRUD'), (students.utils.enums.Colleges['colplant'], 'COLPLANT')], max_length=10, null=True)),
                ('department', models.CharField(choices=[(students.utils.enums.Departments['ele'], 'ELE'), (students.utils.enums.Departments['mte'], 'MTE'), (students.utils.enums.Departments['mce'], 'MCE'), (students.utils.enums.Departments['abe'], 'ABE'), (students.utils.enums.Departments['cve'], 'CVE'), (students.utils.enums.Departments['bch'], 'BCH'), (students.utils.enums.Departments['mcb'], 'MCB'), (students.utils.enums.Departments['paz'], 'PAZ'), (students.utils.enums.Departments['pab'], 'PAB')], max_length=5, null=True)),
                ('blood_type', models.CharField(choices=[(students.utils.enums.BloodTypes['a_positive'], 'A+'), (students.utils.enums.BloodTypes['a_negative'], 'A-'), (students.utils.enums.BloodTypes['b_positive'], 'B+'), (students.utils.enums.BloodTypes['b_negative'], 'B-'), (students.utils.enums.BloodTypes['o_positive'], 'O+'), (students.utils.enums.BloodTypes['o_negative'], 'O-'), (students.utils.enums.BloodTypes['ab_positive'], 'AB+'), (students.utils.enums.BloodTypes['ab_negative'], 'AB-')], max_length=15, null=True)),
                ('genotype', models.CharField(choices=[(students.utils.enums.GenoTypes['AA'], 'AA'), (students.utils.enums.GenoTypes['AS'], 'AS'), (students.utils.enums.GenoTypes['AC'], 'AC'), (students.utils.enums.GenoTypes['SS'], 'SS'), (students.utils.enums.GenoTypes['SC'], 'SC'), (students.utils.enums.GenoTypes['CC'], 'CC')], max_length=2, null=True)),
                ('level', models.CharField(choices=[(students.utils.enums.StudentLevels['first_year'], '100L'), (students.utils.enums.StudentLevels['second_year'], '200L'), (students.utils.enums.StudentLevels['third_year'], '300L'), (students.utils.enums.StudentLevels['fourth_year'], '400L'), (students.utils.enums.StudentLevels['fifth_year'], '500L'), (students.utils.enums.StudentLevels['sixth_year'], '600L')], max_length=15, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
