# Generated by Django 3.0.3 on 2020-02-15 22:47

from django.db import migrations, models
import students.utils.enums
import students.utils.generate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=students.utils.generate.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('matric_number', models.CharField(max_length=8, unique=True)),
                ('department', models.CharField(choices=[(students.utils.enums.Departments['ele'], 'ELE'), (students.utils.enums.Departments['mte'], 'MTE'), (students.utils.enums.Departments['mce'], 'MCE'), (students.utils.enums.Departments['abe'], 'ABE'), (students.utils.enums.Departments['cve'], 'CVE'), (students.utils.enums.Departments['bch'], 'BCH'), (students.utils.enums.Departments['mcb'], 'MCB'), (students.utils.enums.Departments['paz'], 'PAZ'), (students.utils.enums.Departments['pab'], 'PAB')], max_length=5, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
