# Generated by Django 3.0.3 on 2020-02-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_active',
            new_name='is_confirmed',
        ),
    ]
