# Generated by Django 3.0.3 on 2020-02-29 01:57

from django.db import migrations, models
import django.db.models.deletion
import students.utils.generate


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200224_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListedToken',
            fields=[
                ('id', models.CharField(default=students.utils.generate.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
