# Generated by Django 3.0.3 on 2020-03-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='blood_type',
            new_name='blood_group',
        ),
        migrations.AddField(
            model_name='student',
            name='clinic_number',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
