# Generated by Django 3.0.3 on 2020-03-03 01:21

from django.db import migrations, models
import django.db.models.deletion
import students.utils.generate


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(default=students.utils.generate.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='blood_type',
            new_name='blood_group',
        ),
        migrations.AddField(
            model_name='student',
            name='clinic_number',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
        migrations.AddField(
            model_name='token',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
