# Generated by Django 3.0.3 on 2020-03-03 02:03

from django.db import migrations, models
import django.db.models.deletion
import students.utils.generate


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200303_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.CharField(default=students.utils.generate.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
