# Generated by Django 3.0.3 on 2020-03-06 15:54

from django.db import migrations, models
import students.utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[(students.utils.enums.Departments['ele'], 'ELE'), (students.utils.enums.Departments['mte'], 'MTE'), (students.utils.enums.Departments['mce'], 'MCE'), (students.utils.enums.Departments['abe'], 'ABE'), (students.utils.enums.Departments['cve'], 'CVE'), (students.utils.enums.Departments['bch'], 'BCH'), (students.utils.enums.Departments['mcb'], 'MCB'), (students.utils.enums.Departments['paz'], 'PAZ'), (students.utils.enums.Departments['pab'], 'PAB'), (students.utils.enums.Departments['emt'], 'EMT'), (students.utils.enums.Departments['wma'], 'WMA'), (students.utils.enums.Departments['aqfm'], 'AQFM'), (students.utils.enums.Departments['fwm'], 'FWM'), (students.utils.enums.Departments['agad'], 'AGAD'), (students.utils.enums.Departments['aefm'], 'AEFM'), (students.utils.enums.Departments['aerd'], 'AERD'), (students.utils.enums.Departments['eco'], 'ECO'), (students.utils.enums.Departments['ets'], 'ETS'), (students.utils.enums.Departments['acc'], 'ACC'), (students.utils.enums.Departments['bfn'], 'BFN'), (students.utils.enums.Departments['bam'], 'BAM'), (students.utils.enums.Departments['chm'], 'CHM'), (students.utils.enums.Departments['csc'], 'CSC'), (students.utils.enums.Departments['mts'], 'MTS'), (students.utils.enums.Departments['phs'], 'PHS'), (students.utils.enums.Departments['sts'], 'STS'), (students.utils.enums.Departments['abg'], 'ABG'), (students.utils.enums.Departments['ann'], 'ANN'), (students.utils.enums.Departments['anp'], 'ANP'), (students.utils.enums.Departments['aph'], 'APH'), (students.utils.enums.Departments['prm'], 'PRM'), (students.utils.enums.Departments['sslm'], 'SSLM'), (students.utils.enums.Departments['ppcp'], 'PPCP'), (students.utils.enums.Departments['pbst'], 'PBST'), (students.utils.enums.Departments['hrt'], 'HRT'), (students.utils.enums.Departments['cpt'], 'CPT'), (students.utils.enums.Departments['fst'], 'FST'), (students.utils.enums.Departments['hsm'], 'HSM'), (students.utils.enums.Departments['ntd'], 'NTD'), (students.utils.enums.Departments['htm'], 'HTM'), (students.utils.enums.Departments['vet'], 'VET')], max_length=5, null=True),
        ),
    ]
