# Generated by Django 3.0.3 on 2020-03-14 17:39

from django.db import migrations, models
import students.utils.enums
import students.utils.generate


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200312_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='student',
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.CharField(default=students.utils.generate.generate_id, max_length=12),
        ),
        migrations.AddField(
            model_name='token',
            name='user_table',
            field=models.CharField(choices=[(students.utils.enums.UserTypes['student'], 'Student'), (students.utils.enums.UserTypes['worker'], 'Worker')], default=students.utils.enums.UserTypes['student'], max_length=20),
        ),
    ]
