# Generated by Django 3.0.3 on 2020-04-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20200316_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/health-app-1583346005925.appspot.com/o/users_avatar%2Fbfgi7tfn6yob_Habeeb.jpg?alt=media&token=25a96e7b-5c33-465c-9924-6f7ede337ed6'),
        ),
    ]
