# Generated by Django 3.0.3 on 2020-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200420_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('pending', 'pending'), ('ignored', 'ignored')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('ELE', 'ELE'), ('MTE', 'MTE'), ('MCE', 'MCE'), ('ABE', 'ABE'), ('CVE', 'CVE'), ('BCH', 'BCH'), ('MCB', 'MCB'), ('PAZ', 'PAZ'), ('PAB', 'PAB'), ('EMT', 'EMT'), ('WMA', 'WMA'), ('AQFM', 'AQFM'), ('FWM', 'FWM'), ('AGAD', 'AGAD'), ('AEFM', 'AEFM'), ('AERD', 'AERD'), ('ECO', 'ECO'), ('ETS', 'ETS'), ('ACC', 'ACC'), ('BFN', 'BFN'), ('BAM', 'BAM'), ('CHM', 'CHM'), ('CSC', 'CSC'), ('MTS', 'MTS'), ('PHS', 'PHS'), ('STS', 'STS'), ('ABG', 'ABG'), ('ANN', 'ANN'), ('ANP', 'ANP'), ('APH', 'APH'), ('PRM', 'PRM'), ('SSLM', 'SSLM'), ('PPCP', 'PPCP'), ('PBST', 'PBST'), ('HRT', 'HRT'), ('CPT', 'CPT'), ('FST', 'FST'), ('HSM', 'HSM'), ('NTD', 'NTD'), ('HTM', 'HTM'), ('VET', 'VET')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='user_table',
            field=models.CharField(choices=[('Student', 'Student'), ('Worker', 'Worker')], default='Student', max_length=20),
        ),
    ]
