# Generated by Django 3.0.3 on 2020-03-17 10:09

from django.db import migrations, models
import students.utils.generate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.CharField(default=students.utils.generate.generate_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ailment', models.CharField(default='Title', max_length=250)),
                ('symptoms', models.CharField(default='Symptoms', max_length=2000)),
                ('causes', models.CharField(default='Causes', max_length=2000)),
                ('dos', models.CharField(default='Dos', max_length=2000)),
                ('donts', models.CharField(default="Don'ts", max_length=2000)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated_at', '-views'],
            },
        ),
    ]
