# Generated by Django 3.0.3 on 2020-03-17 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstaid', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tip',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
