# Generated by Django 3.0.3 on 2020-03-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcentre', '0002_iot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='iot',
            name='password',
        ),
    ]
